version: '3.8'

services:
  redis:
    container_name: Redis
    image: redis:latest
    ports:
      - 6379:6379

  sqlserver:
    container_name: MsSqlServer
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "pa$$w0rd!"
    ports:
      - 1433:1433

  rabbitmq:
    container_name: RabbitMQ
    image: rabbitmq:management
    hostname: "rabbit1"
    ports:
      - 15672:15672
      - 5672:5672
    labels:
      NAME: "some-rabbit"