version: '3.8'

services:
  redis:
    container_name: Redis
    image: redis:latest
    ports:
      - 6379:6379

  sqlserver:
    container_name: MsSqlServer
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "pa$$w0rd!"
    ports:
      - 1433:1433

  mongo:
    container_name: MongoDb
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    container_name: RabbitMQ
    image: rabbitmq:management
    hostname: "rabbit1"
    ports:
      - 15672:15672
      - 5672:5672
    labels:
      NAME: "some-rabbit"

  portainer:
    container_name: Portainer
    image: portainer/portainer-ce
    ports:
      - 9443:9443
      - 8080:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  mongo_data:
  portainer_data:
  #postgres_data:
  #pgadmin_data:
  #elasticsearch-data: